# Generated by Django 4.0.6 on 2023-04-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='Question',
        ),
    ]
