# Generated by Django 4.0.6 on 2023-04-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0002_rename_question_choice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='Question',
            new_name='question',
        ),
    ]
