# Generated by Django 4.0.6 on 2023-04-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0004_rename_question_questionar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questionar',
            new_name='Question',
        ),
    ]
