# Generated by Django 4.2.1 on 2023-07-04 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Balancete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("data", models.DateTimeField(verbose_name="Data do Balancete")),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("senha", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Lancamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
                (
                    "balancete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financas.balancete",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="balancete",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="financas.usuario"
            ),
        ),
    ]
