# Generated by Django 4.2.1 on 2023-07-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamento",
            name="foto",
            field=models.ImageField(
                default="..static/img/financas/DiagramaDominioFinancas.png",
                upload_to="../static/img/financas",
            ),
        ),
        migrations.AddField(
            model_name="lancamento",
            name="valor",
            field=models.FloatField(default=0.0),
        ),
    ]
