# Generated by Django 4.2.1 on 2023-07-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financas", "0002_lancamento_foto_lancamento_valor"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamento",
            name="despesa",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lancamento",
            name="foto",
            field=models.ImageField(
                default="static/img/financas/DiagramaDominioFinancas.png",
                upload_to="static/img/financas",
            ),
        ),
    ]
