# Generated by Django 4.2.1 on 2023-07-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financas", "0003_lancamento_despesa_usuario_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lancamento",
            name="foto",
            field=models.ImageField(
                default="static/financas/img/DiagramaDominioFinancas.png",
                upload_to="static/img/financas",
            ),
        ),
    ]
