# Generated by Django 4.2.1 on 2023-07-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financas", "0005_alter_lancamento_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lancamento",
            name="foto",
            field=models.ImageField(
                default="financas/img/DiagramaDominioFinancas.png",
                upload_to="static/img/financas",
            ),
        ),
    ]
