# Generated by Django 4.2.1 on 2023-07-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financas", "0006_alter_lancamento_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lancamento",
            name="foto",
            field=models.ImageField(
                default="img/financas/DiagramaDominioFinancas.png",
                upload_to="mysite/media/img/financas",
            ),
        ),
    ]
