# Generated by Django 4.2.1 on 2023-07-21 03:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("financas", "0007_alter_lancamento_foto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="balancete",
            options={"verbose_name_plural": "Balancetes"},
        ),
        migrations.AlterModelOptions(
            name="lancamento",
            options={"verbose_name_plural": "Lançamentos"},
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={"verbose_name_plural": "Usuarios"},
        ),
        migrations.RemoveField(
            model_name="balancete",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="senha",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="status",
        ),
    ]
