# Generated by Django 4.2.1 on 2023-07-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financas", "0008_alter_balancete_options_alter_lancamento_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="apelido",
            field=models.CharField(default="", max_length=200),
        ),
    ]
