# Generated by Django 4.2.1 on 2023-07-26 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financas", "0010_balancete_usuario_usuario_usuario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balancete",
            name="usuario",
            field=models.ForeignKey(
                default="5",
                on_delete=django.db.models.deletion.CASCADE,
                to="financas.usuario",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="usuario",
            field=models.OneToOneField(
                default="5",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
