# Generated by Django 4.2.1 on 2023-07-26 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financas", "0012_alter_balancete_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
