# Generated by Django 4.2.1 on 2023-07-26 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financas", "0014_remove_balancete_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancete",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="financas.usuario",
            ),
        ),
    ]
