# Generated by Django 4.2.1 on 2023-07-26 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("financas", "0016_alter_balancete_usuario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="usuario",
            new_name="user",
        ),
    ]
