# Generated by Django 4.2.1 on 2023-07-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financas", "0018_rename_apelido_usuario_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lancamento",
            name="foto",
            field=models.ImageField(
                default="mysite/media/img/financas/DiagramaDominioFinancas.png",
                upload_to="img/financas/",
            ),
        ),
    ]
