# Generated by Django 4.2.1 on 2023-07-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financas", "0019_alter_lancamento_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lancamento",
            name="foto",
            field=models.ImageField(
                default="media/img/financas/DiagramaDominioFinancas.png",
                upload_to="media/img/financas/",
            ),
        ),
    ]
