# Generated by Django 4.2.3 on 2023-07-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0021_alter_lancamento_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='foto',
            field=models.ImageField(default='DiagramaDominioFinancas.png', upload_to='img/financas/'),
        ),
    ]
