# Generated by Django 4.2.3 on 2023-07-27 11:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('matricula', models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=100)),
                ('num_aulas', models.IntegerField(default=0)),
                ('ano', models.IntegerField(default=0)),
                ('semestre', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('carga_horaria', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.IntegerField(default=0)),
                ('nota2', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('num_faltas', models.IntegerField(default=0)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.aluno')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.diario')),
            ],
        ),
        migrations.AddField(
            model_name='diario',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.disciplina'),
        ),
    ]
