# Generated by Django 4.2.1 on 2023-07-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lablivre", "0002_remove_computador_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="laboratorio",
            name="ligados",
            field=models.IntegerField(default=0),
        ),
    ]
