# Generated by Django 4.2.1 on 2023-07-07 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lablivre", "0003_laboratorio_ligados"),
    ]

    operations = [
        migrations.RenameField(
            model_name="laboratorio",
            old_name="ligados",
            new_name="desligados",
        ),
    ]
