# Generated by Django 4.2.1 on 2023-07-07 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lablivre", "0004_rename_ligados_laboratorio_desligados"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laboratorio",
            name="desligados",
        ),
    ]
