# Generated by Django 4.2.1 on 2023-07-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lablivre", "0005_remove_laboratorio_desligados"),
    ]

    operations = [
        migrations.AddField(
            model_name="computador",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
