# Generated by Django 4.2.1 on 2023-07-08 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lablivre", "0006_computador_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="computador",
            old_name="mac",
            new_name="patrimonio",
        ),
        migrations.RemoveField(
            model_name="computador",
            name="desligado",
        ),
        migrations.RemoveField(
            model_name="computador",
            name="status",
        ),
        migrations.CreateModel(
            name="Mac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mac", models.CharField(max_length=200)),
                (
                    "computador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lablivre.computador",
                    ),
                ),
            ],
        ),
    ]
