# Generated by Django 4.2.1 on 2023-07-21 03:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lablivre", "0007_rename_mac_computador_patrimonio_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="computador",
            options={"verbose_name_plural": "Computadores"},
        ),
        migrations.AlterModelOptions(
            name="laboratorio",
            options={"verbose_name_plural": "Laboratórios"},
        ),
        migrations.AddField(
            model_name="computador",
            name="identificador",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.DeleteModel(
            name="Mac",
        ),
    ]
